# Generated by Django 4.2.13 on 2025-09-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='ref',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
