# Generated by Django 5.0.14 on 2025-05-30 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('general', 'General'), ('user', 'User')], help_text='The type of notification.', max_length=50, verbose_name='Notification Type')),
                ('title', models.CharField(help_text='The title of the notification.', max_length=255, verbose_name='Title')),
                ('message', models.TextField(help_text='The content of the notification.', verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the notification was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the notification was last updated.', verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the notification is currently active.', verbose_name='Is Active')),
                ('tag', models.CharField(choices=[('info', 'Information'), ('alert', 'Alert'), ('reminder', 'Reminder')], help_text='The tag associated with the notification.', max_length=50, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'General Notification',
                'verbose_name_plural': 'General Notifications',
            },
            bases=('notifications.notification',),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates if the notification has been read by the user.', verbose_name='Is Read')),
                ('user', models.ForeignKey(help_text='The user to whom the notification is sent.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
            },
            bases=('notifications.notification',),
        ),
    ]
