# Generated by Django 5.0.14 on 2025-06-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='fulfilled',
            field=models.BooleanField(default=False, help_text='Indicates if the contribution has been fulfilled.', verbose_name='Fulfilled'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The amount contributed towards the service.', max_digits=10, null=True, verbose_name='Amount'),
        ),
    ]
