# Generated by Django 5.0.14 on 2025-06-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0002_contribution_fulfilled_alter_contribution_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteercontribution',
            name='service',
            field=models.ForeignKey(help_text='The service for which the volunteer contribution is made.', on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='registries.service', verbose_name='Service'),
        ),
    ]
