# Generated by Django 5.0.14 on 2025-06-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0003_alter_volunteercontribution_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cashed_out',
            field=models.BooleanField(default=False, help_text='Indicates if the service has been cashed out.', verbose_name='Cashed Out'),
        ),
    ]
