# Generated by Django 5.0.14 on 2025-06-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0004_service_cashed_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultregistry',
            name='default_services',
            field=models.ManyToManyField(default=[], help_text='The default services included in this registry template.', related_name='default_registries', to='registries.defaultservice', verbose_name='Services'),
        ),
    ]
