# Generated by Django 5.0.14 on 2025-06-24 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0006_alter_defaultregistry_default_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='allow_volunteers',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cashed_out',
        ),
        migrations.AddField(
            model_name='contribution',
            name='message',
            field=models.TextField(blank=True, help_text='An optional message from the contributor.', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='service',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The total amount withdrawn for this service.', max_digits=10, verbose_name='Total Withdrawn'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(blank=True, help_text='The user who made the contribution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Contributor'),
        ),
        migrations.DeleteModel(
            name='VolunteerContribution',
        ),
    ]
