# Generated by Django 5.0.14 on 2025-07-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0007_remove_service_allow_volunteers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='thank_you_message',
            field=models.TextField(blank=True, help_text='A thank you message for contributors to the registry.', verbose_name='Thank You Message'),
        ),
        migrations.AddField(
            model_name='registry',
            name='welcome_message',
            field=models.TextField(blank=True, help_text='A welcome message for the registry.', verbose_name='Welcome Message'),
        ),
    ]
