# Generated by Django 4.2.13 on 2025-09-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0008_registry_thank_you_message_registry_welcome_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='fulfilled',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='summary',
        ),
        migrations.AddField(
            model_name='contribution',
            name='contributor_email',
            field=models.EmailField(blank=True, help_text='The email of the person contributing.', max_length=254, verbose_name='Contributor Email'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='contributor_name',
            field=models.CharField(blank=True, help_text='The name of the person contributing.', max_length=100, verbose_name='Contributor Name'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(default='succeeded', help_text='The status of the payment from Stripe.', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Stripe Payment Intent ID'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount contributed towards the service.', max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='service',
            field=models.ForeignKey(help_text='The service for which the contribution is made.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='registries.service', verbose_name='Service'),
        ),
    ]
