# Generated by Django 4.2.13 on 2025-09-11 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0009_remove_contribution_contributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedregistry',
            name='registry',
            field=models.ForeignKey(help_text='The registry that is shared.', on_delete=django.db.models.deletion.CASCADE, related_name='shared_registry', to='registries.registry', verbose_name='Registry'),
        ),
    ]
