# Generated by Django 4.2.13 on 2025-09-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0010_alter_sharedregistry_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='Status')),
                ('stripe_transfer_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Stripe Transfer ID')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='registries.registry', verbose_name='Registry')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
            },
        ),
    ]
