# Generated by Django 4.2.13 on 2025-09-20 21:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0011_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The processing fee charged by the payment provider.', max_digits=10, verbose_name='Processing Fee'),
        ),
    ]
