# Generated by Django 4.2.13 on 2025-09-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0012_contribution_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='available_on',
            field=models.DateTimeField(blank=True, help_text='The date and time when the funds from this contribution will be available.', null=True, verbose_name='Available On'),
        ),
    ]
