# Generated by Django 5.0.4 on 2025-09-23 10:00

from django.db import migrations
from decimal import Decimal


def populate_default_services(apps, schema_editor):
    """
    Populates the DefaultService table with a curated list of services.
    """
    DefaultService = apps.get_model('registries', 'DefaultService')
    db_alias = schema_editor.connection.alias

    default_services_data = [
        # Home & Household Harmony
        {'name': 'The Tidy-Up Crew (House Cleaning)', 'description': 'Gift the new parents a sparkling clean and peaceful home. This contribution covers a professional cleaning session, giving them more time to rest and bond with the baby, and less time worrying about chores.', 'hours': 4, 'cost_per_hour': Decimal('40.00')},
        {'name': 'The Laundry Lifesaver', 'description': 'Baby laundry piles up fast! Help lighten the load with a professional laundry service. This gift means fresh, clean clothes for the baby and parents without the endless cycle of washing, drying, and folding.', 'hours': 3, 'cost_per_hour': Decimal('35.00')},
        {'name': 'The Errand Runner', 'description': 'From picking up groceries to dropping off packages, errands can be overwhelming with a newborn. Your contribution helps hire a trusted helper to tackle the to-do list, giving the new parents precious time back.', 'hours': 2, 'cost_per_hour': Decimal('30.00')},
        {'name': 'The Outdoor Oasis (Lawn & Yard Care)', 'description': 'Help maintain a beautiful outdoor space for the family to enjoy. This contribution covers lawn mowing and yard work, ensuring the outside of their home is as peaceful as the inside.', 'hours': 2, 'cost_per_hour': Decimal('50.00')},

        # Nourishment & Meal Support
        {'name': 'The Nourished Mom (Meal Prep & Delivery)', 'description': 'A well-fed mom is a happy mom! Contribute to delicious, healthy, and ready-to-eat meals. This gift takes the stress of cooking off their plate, so they can focus on nourishing their new baby.', 'hours': 4, 'cost_per_hour': Decimal('50.00')},
        {'name': 'The Stocked Pantry (Grocery Shopping & Delivery)', 'description': 'Help keep the kitchen full of healthy snacks and essentials. This contribution covers the time and effort of grocery shopping, ensuring the new family has everything they need without leaving the house.', 'hours': 2, 'cost_per_hour': Decimal('30.00')},

        # Baby & Mom Care
        {'name': 'The Postpartum Doula Fund', 'description': 'A postpartum doula provides invaluable emotional, physical, and informational support to the new mother and family. Your contribution helps them hire an expert guide for this transformative period.', 'hours': 8, 'cost_per_hour': Decimal('50.00')},
        {'name': 'The Night Owl (Overnight Newborn Care)', 'description': 'The gift of sleep is priceless. Contribute to a night of care from a newborn specialist, allowing the new parents to get a full night of uninterrupted rest and recharge for the days ahead.', 'hours': 8, 'cost_per_hour': Decimal('45.00')},
        {'name': 'The Lactation Lifeline (Lactation Consultant)', 'description': "Support the new mom's feeding journey by contributing to a session with a professional lactation consultant. This expert guidance can provide confidence and peace of mind during a crucial time.", 'hours': 2, 'cost_per_hour': Decimal('125.00')},
        {'name': 'A Helping Hand (Daytime Babysitting)', 'description': 'Give the new mom a few hours to herself to nap, shower, or simply relax. This contribution provides a trusted babysitter to care for the little one, offering a much-needed break.', 'hours': 4, 'cost_per_hour': Decimal('25.00')},
        {'name': 'The Fur-Baby Sitter (Pet Care)', 'description': "Don't forget the furry members of the family! Help care for the family pet with dog walking or pet sitting services, ensuring every member of the household feels loved and looked after.", 'hours': 2, 'cost_per_hour': Decimal('25.00')},
        {'name': 'The Sibling Sidekick', 'description': 'Help older siblings feel special and included! This contribution funds a fun activity or a dedicated babysitter for the older child, giving them quality attention and allowing the parents to focus on the newborn.', 'hours': 3, 'cost_per_hour': Decimal('25.00')},

        # Wellness & Recovery
        {'name': 'The Recovery Retreat (Postnatal Massage)', 'description': 'Help the new mom heal and relax with a professional postnatal massage. This therapeutic session is designed to relieve tension, reduce stress, and support her physical recovery after childbirth.', 'hours': 1, 'cost_per_hour': Decimal('120.00')},
        {'name': 'The Polished Pause (Manicure)', 'description': "A little bit of pampering goes a long way. Gift the new mom a professional manicure, giving her a moment of self-care and a touch of polish to brighten her day. It's a small luxury that makes a big difference.", 'hours': 1, 'cost_per_hour': Decimal('45.00')},
        {'name': 'The Tired Toes Treat (Pedicure)', 'description': 'Nine months of carrying extra weight is tough on the feet! Contribute to a relaxing and rejuvenating pedicure to soothe her tired feet and give her a well-deserved moment of pampering.', 'hours': 1, 'cost_per_hour': Decimal('65.00')},
        {'name': 'The Pelvic Floor Restore Fund', 'description': "Contribute to a vital part of postpartum recovery. This fund helps the new mom see a specialized pelvic floor physical therapist to regain strength and function, ensuring her long-term health and well-being.", 'hours': 1, 'cost_per_hour': Decimal('175.00')},
        {'name': 'The Mindful Moment (Mental Health Support)', 'description': "Support the new mom's mental and emotional health by contributing to a therapy or counseling session. This gift provides a safe space for her to navigate the challenges and joys of new motherhood.", 'hours': 1, 'cost_per_hour': Decimal('150.00')},
    ]

    for service_data in default_services_data:
        DefaultService.objects.using(db_alias).update_or_create(
            name=service_data['name'],
            defaults=service_data
        )


def remove_default_services(apps, schema_editor):
    """
    Removes the default services created by the populate_default_services function.
    This is the reverse operation for the migration.
    """
    DefaultService = apps.get_model('registries', 'DefaultService')
    db_alias = schema_editor.connection.alias

    # The names of the services to be removed.
    service_names = [
        'The Tidy-Up Crew (House Cleaning)',
        'The Laundry Lifesaver',
        'The Errand Runner',
        'The Outdoor Oasis (Lawn & Yard Care)',
        'The Nourished Mom (Meal Prep & Delivery)',
        'The Stocked Pantry (Grocery Shopping & Delivery)',
        'The Postpartum Doula Fund',
        'The Night Owl (Overnight Newborn Care)',
        'The Lactation Lifeline (Lactation Consultant)',
        'A Helping Hand (Daytime Babysitting)',
        'The Fur-Baby Sitter (Pet Care)',
        'The Sibling Sidekick',
        'The Recovery Retreat (Postnatal Massage)',
        'The Polished Pause (Manicure)',
        'The Tired Toes Treat (Pedicure)',
        'The Pelvic Floor Restore Fund',
        'The Mindful Moment (Mental Health Support)',
    ]

    DefaultService.objects.using(db_alias).filter(name__in=service_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0013_contribution_available_on'),
    ]

    operations = [
        migrations.RunPython(populate_default_services, remove_default_services),
    ]
