# Generated by Django 5.0.4 on 2025-10-26 12:00

from django.db import migrations
from decimal import Decimal


def populate_new_default_services(apps, schema_editor):
    """
    Populates the DefaultService table with new services.
    """
    DefaultService = apps.get_model('registries', 'DefaultService')
    db_alias = schema_editor.connection.alias

    new_services_data = [
        {
            'name': 'The Organized Momma (Virtual Assistant)',
            'description': 'Help the new mom stay on top of everything without the stress. This contribution provides a virtual assistant to manage schedules, handle administrative tasks, and organize appointments, freeing up her time to focus on what truly matters: her new baby.',
            'hours': 10,
            'cost_per_hour': Decimal('25.00')
        },
        {
            'name': 'The Strong Momma (Personal Trainer)',
            'description': 'Support her postpartum recovery journey with a certified personal trainer. This gift provides tailored fitness sessions to help her safely regain strength, boost energy, and feel her best, all on her own schedule.',
            'hours': 5,
            'cost_per_hour': Decimal('50.00')
        },
    ]

    for service_data in new_services_data:
        DefaultService.objects.using(db_alias).update_or_create(
            name=service_data['name'],
            defaults=service_data
        )


def remove_new_default_services(apps, schema_editor):
    """
    Removes the default services created by this migration.
    """
    DefaultService = apps.get_model('registries', 'DefaultService')
    db_alias = schema_editor.connection.alias
    service_names = ['The Organized Momma (Virtual Assistant)', 'The Strong Momma (Personal Trainer)']
    DefaultService.objects.using(db_alias).filter(name__in=service_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0014_populate_default_services'),
    ]

    operations = [
        migrations.RunPython(populate_new_default_services, remove_new_default_services),
    ]