# Generated by Django 4.2.13 on 2026-01-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0015_add_new_default_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Stripe Transfer ID'),
        ),
    ]
